use_frameworks!

target 'JSCardProcessor_Example' do
  pod 'JSCardProcessor', :path => '../'

  target 'JSCardProcessor_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
